### ISSUE TITLE
404 on "previous editions" pages

### ISSUE THREAD

**Issue by mstred** [geeknightrecife/geeknightrecife.github.io#7]
![screen shot 2016-02-25 at 2 26 28 pm](https://cloud.githubusercontent.com/assets/1061950/13328138/deeabe0c-dbcb-11e5-9717-c786a647db51.png)

**Comment by justinharringa** [comment]
Should be fixed by e32d8cfa05aab01e09e3e37a594141fedf454d56 and 65b4f233c6a18093dde451796b46d757eafd738a
